### ISSUE TITLE
Add back button to Drawer Navigator

### ISSUE THREAD

**Issue by Er-rchydy** [nathvarun/React-Native-Firebase-Tutorials#2]

**Comment by Er-rchydy** [comment]
I tried to add a back button but it didn't work. 
here is what i did: 
i set `backBehavior` to` none` like this
```
const MyApp = DrawerNavigator({
  Home: {
    screen: homeScreen
  },
  Contact: {
    screen: ContactScreen
  },
  New: {
    screen: NewScreen
  }
},
  {
    initialRouteName: 'Home',
    drawerPosition: 'left',
    backBehavior: 'none',
    contentComponent: CustomDrawerContentComponent,
    drawerOpenRoute: 'DrawerOpen',
    drawerCloseRoute: 'DrawerClose',
    drawerToggleRoute: 'DrawerToggle'
  });
```

then send the `goBack` method with `drawerOpen` to `CustomHeader` like this:
```
<CustomHeader 
                    title="Soccer"
                    drawerOpen={() => this.props.navigation.openDrawer()} 
                    goBack={() => this.props.navigation.goBack()}   // i tried goBack(null) but it didn't work either
                    />
```

then i added this to `CustomHeader.js`
```
<Right>
      <Icon style={{color: 'white', fontSize: 40}} name="arrow-back" onPress={() => this.props.goBack()} />
</Right>
```

but none of them work in a proper way.
when i remove 'backBehavior: 'none'' or set 'backBehavior: 'initialRoute'',  the back button work with no issue, it always send me to the initial screen (obvious because i set `backBehavior` to `initialRoute`, and it work too when i remove it because `initialRoute` is the default value of `backBehavior` ).
i don't know how to make it work like this: when i click Back button to take me to the previous screen not to the initial screen.
thanks for the awesome examples.

**Comment by nathvarun** [comment]
In case you haven't figured this out already.
The Drawer navigator is not meant to work the way you are expecting it to. 
It is not meant to allow you to go back to the previous screen.

backbehavior: 
'none' -> you will be taken out of the app if a drawer is your root navigator
'initialRoute' - you will be taken to the initial route of the DrawerNavigator
